
# Use a base image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the .js file to the working directory
COPY . .

# Specify the command to run when the container starts
CMD ["npm", "run", "start"]
